image: ubuntu

before_script:
  - apt-get update --yes
  - apt-get install --yes cmake gcc g++

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
    - cmake --build build --parallel $(nproc)
  artifacts:
    paths:
      - build
    expire_in: 20min
    
unit-test-job:
  stage: test
  script:
    - cmake --build build --target test
